name: weather_app
description: Ứng dụng thời tiết - Mã đề 36 - Chuyên đề 2
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_vibrate: ^1.3.0
  google_generative_ai: ^0.4.7
  get: ^4.6.6
  flutter_markdown: ^0.7.3
  # THÊM 2 THƯ VIỆN NÀY
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
